apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-deploy
spec:
   replicas: 2
   selector:
       matchLabels:
          app: devops
   template:
       metadata:
          labels:          
             app: devops
       spec:
          containers:
          - name: devops-container
            image: ariharasudhanr/devops:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 80